name: Spring-Petclinic.GCR.AKS

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
      - Rajesh

jobs:
  GCR_Push:
   name: build and push to GCR
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-package: 1.9
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build with Maven
      run: mvn -B package --file pom.xml 
           
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
        
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/grenston/petclinic:latest
          ghcr.io/grenston/petclinic:${{ steps.date.outputs.date }}.${{ github.run_number }}
          
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
 #  
  # build:
  #   name: build and push to DockerHub
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #     name: Checkout
    
  #   - name: Set up JDK 1.8
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: 1.8
    
  #   - name: Build with Maven
  #     run: mvn -B package --file pom.xml      
                 
  #   - name: Docker login
  #     uses: azure/docker-login@v1
  #     with:
  #       login-server: https://index.docker.io/v1
  #       username: ${{ secrets.REGISTRY_USERNAME }}
  #       password: ${{ secrets.REGISTRY_PASSWORD }}
    
  #   - name: Install Trivy
  #     run: |
  #       sudo apt-get install wget apt-transport-https gnupg lsb-release
  #       wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
  #       echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
  #       sudo apt-get update
  #       sudo apt-get install trivy
  #       echo $HOME/Library/Caches
    
  #   - name: build, scan and tag image
  #     run: |
  #       docker build -f ./Dockerfile -t ${{ secrets.REGISTRY_USERNAME }}/spring-petclinic:${{ github.run_number }} .
  #       trivy --exit-code 0 --severity MEDIUM,HIGH ${{ secrets.REGISTRY_USERNAME }}/spring-petclinic:${{ github.run_number }}
       
  #   - name: push image to dockerhub
  #     run: |
  #       docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
  #       docker push ${{ secrets.REGISTRY_USERNAME }}/spring-petclinic:${{ github.run_number }}
#--------------------
