# This workflow integrates a collection of open source static analysis tools
# with GitHub code scanning. For documentation, or to provide feedback, visit
# https://github.com/github/ossar-action
name: OSSAR

on:
  push:

jobs:
  OSSAR-Scan:
    # OSSAR runs on windows-latest.
    # ubuntu-latest and macos-latest support coming soon
    runs-on: windows-latest

    steps:
      # Checkout your code repository to scan
    - name: Checkout repository
      uses: actions/checkout@v2
    
      # Install dotnet, used by OSSAR
    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201'
    
    - name: Create a folder
      run: |
        mkdir d:\a\_msca\versions\temp
        dir
        
      # Run open source static analysis tools
    - name: Run OSSAR
      uses: github/ossar-action@v1
      id: ossar
      with:
        policy: d:\a\_actions\github\ossar-action\v1\policy\github.gdnpolicy

      # Upload results to the Security tab
    - name: Upload OSSAR results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.ossar.outputs.sarifFile }}
